<?php
namespace CroudTech\RecurringTaskScheduler\Model;

use Carbon\Carbon;
use CroudTech\RecurringTaskScheduler\Model\Schedule;
use Illuminate\Database\Eloquent\Model;

/**
 * The ScheduleEvent represents a single date generated by a schedule.
 *
 * Datetime values stored in the ScheduleEvent are stored in UTC (Timezone offsets are assumed to have been calculated at generation time)
 * and a copy of the original datetime with it's timezone are stored for reporting and debugging
 *
 */
class ScheduleEvent extends Model
{
    protected $fillable = [
        'date',
    ];

    protected $casts = [
        'triggered_at' => 'datetime',
    ];

    /**
     * Schedule relationship
     *
     * @return void
     */
    public function schedule()
    {
        return $this->belongsTo(Schedule::class);
    }

    /**
     * Trigger the callback on the schedule
     *
     * @return bool
     */
    public function trigger() : bool
    {
        $return_value = $this->schedule->trigger($this);
        if ($return_value === true) {
            $this->triggered_at = $this->schedule->triggered_at;
            $this->save();
        }

        return $return_value;
    }
}
