<?php
namespace CroudTech\RecurringTaskScheduler\Model;

use Illuminate\Database\Eloquent\Model;

/**
 * The ScheduleEvent represents a single date generated by a schedule.
 *
 * Datetime values stored in the ScheduleEvent are stored in UTC (Timezone offsets are assumed to have been calculated at generation time)
 * and a copy of the original datetime with it's timezone are stored for reporting and debugging
 *
 */
class ScheduleEvent extends Model
{

}
